apiVersion: v1
name: conjur-config-namespace-prep
home: https://www.conjur.org
version: 0.1.1
description: A Helm chart which prepares a Namespace for using CyberArk Conjur authenticator clients
icon: https://www.cyberark.com/wp-content/uploads/2015/12/cybr-aim.jpg
keywords:
  - security
  - 'secrets management'
sources:
  - https://github.com/cyberark/conjur-authn-k8s-client
  - https://github.com/cyberark/conjur-oss-helm-chart
  - https://github.com/cyberark/conjur
maintainers:
  - name: Conjur Maintainers
    email: conj_maintainers@cyberark.com
