# Default values for Application Deploy Helm chart
# This is a YAML-formatted file.

global:
  conjur:
    # name of the ConfigMap created by the conjur-config-namespace-prep chart
    conjurConnConfigMap: "conjur-connect-configmap"

  appServiceType: "NodePort"

# Authenticator types to deploy and test. Multiple authenticator types
# can be selected. All enabled authenticator types (along with their
# associated sample application container) will be deployed to the
# same application Namespace. The default (app-summon-sidecar) is to enable only an authn-k8s
# sidecar container. Enable authenticator types as desired.
app-summon-sidecar:
  enabled: true

app-summon-init:
  enabled: false

app-secretless-broker:
  enabled: false

app-secrets-provider:
  enabled: false
