name: Generate K8S Manifests from Helm Charts

on:
  # Run this when PR operations are done
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  generate-k8s-manifests:
    name: Generate K8S manifests via `helm template` command
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kube-tag:
          - v1.18.2
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.2

      - name: Generate manifest for cluster-prep
        run: bin/helm-generate-raw-manifest-cluster-prep.sh

      - name: Generate manifest for namespace-prep
        run: bin/helm-generate-raw-manifest-namespace-prep.sh

      - name: Commit generated manifests
        id: commit-generated-manifests
        run: |
          git add helm/conjur-config-cluster-prep/generated
          git add helm/conjur-config-namespace-prep/generated
          git commit -m "Auto-commit of K8S manifests generated from Helm charts"
        continue-on-error: true

      - name: Push files
        if: steps.commit-generated-manifests.outcome == 'success'
        run: |
          git push --force "https://${{ github.actor }}:${{secrets.GITHUB_TOKEN}}@github.com/${{ github.repository }}.git" "HEAD:$GITHUB_HEAD_REF"
